
const SIZE_XD_DEFAULT = {
    MAIN_SIDE_FRAME_WIDTH: 1821,
    RIGHT_SIDE_FRAME_WIDTH: 1425,
    LEFT_SIDE_FRAME_WIDTH: 1821 - 1425,
};

const SIZE_ELEMENTS_ACTUAL_VIEW_PORT = {
    RIGHT_SIDE_FRAME: (actualViewPortWidth: number) => (SIZE_XD_DEFAULT.RIGHT_SIDE_FRAME_WIDTH / SIZE_XD_DEFAULT.MAIN_SIDE_FRAME_WIDTH) * actualViewPortWidth,
    LEFT_SIDE_FRAME: (actualViewPortWidth: number) => (SIZE_XD_DEFAULT.LEFT_SIDE_FRAME_WIDTH / SIZE_XD_DEFAULT.MAIN_SIDE_FRAME_WIDTH) * actualViewPortWidth,
    MAIN_SIDE_HEIGHT: (actualViewPortWidth: number) => 0.569633192 * actualViewPortWidth
}


export { SIZE_ELEMENTS_ACTUAL_VIEW_PORT }